# Generated by Django 2.2.3 on 2019-07-21 23:32

import django.core.validators
from django.db import migrations, models
import exercise.helpers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioArgenitna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CUIL', 'CUIL'), ('PAS', 'Pasaporte')], max_length=4, verbose_name='tipo documento')),
                ('numero_documento', models.CharField(help_text='Para CUIL usar formato ##-########-#', max_length=13, verbose_name='número de documento')),
                ('nombre', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'El nombre solo permite letras y espacios')], verbose_name='nombre')),
                ('apellido', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'El apellido solo permite letras y espacios')], verbose_name='apellido')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='sexo')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha nacimiento')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('password', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8, 'La contraseña debe contener al menos 8 caracteres')], verbose_name='contraseña')),
                ('validation_level', models.PositiveIntegerField(blank=True, default=exercise.helpers.models.calculate_validation_level, verbose_name='nivel de validacion')),
            ],
            options={
                'unique_together': {('tipo_documento', 'numero_documento')},
            },
        ),
    ]
